# Generated by Django 4.2.7 on 2026-04-22 14:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('patients', '0002_patient_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='consent_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='consent_expiry_date',
            field=models.DateField(blank=True, help_text='Consent valid for 1 year typically', null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='consent_given',
            field=models.BooleanField(default=False, help_text='Has patient signed dialysis consent form?'),
        ),
        migrations.AddField(
            model_name='patient',
            name='hepatitis_b_status',
            field=models.CharField(choices=[('negative', 'Negative'), ('positive', 'Positive'), ('unknown', 'Unknown/Not Tested')], default='unknown', help_text='HBsAg status - Hep B+ patients MUST use dedicated machines', max_length=20),
        ),
        migrations.AddField(
            model_name='patient',
            name='hepatitis_b_vaccinated',
            field=models.BooleanField(default=False, help_text='Is patient Hep B vaccinated?'),
        ),
        migrations.AddField(
            model_name='patient',
            name='hepatitis_c_status',
            field=models.CharField(choices=[('negative', 'Negative'), ('positive', 'Positive'), ('unknown', 'Unknown/Not Tested')], default='unknown', help_text='Anti-HCV status', max_length=20),
        ),
        migrations.AddField(
            model_name='patient',
            name='hiv_status',
            field=models.CharField(choices=[('negative', 'Negative'), ('positive', 'Positive'), ('unknown', 'Unknown/Not Tested')], default='unknown', help_text='HIV status', max_length=20),
        ),
        migrations.AddField(
            model_name='patient',
            name='last_infection_screening_date',
            field=models.DateField(blank=True, help_text='Date of last Hep B/C/HIV screening', null=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='vascular_access',
            field=models.CharField(blank=True, choices=[('av_fistula', 'AV Fistula'), ('av_graft', 'AV Graft'), ('tunneled_catheter', 'Tunneled Catheter (Permcath)'), ('temporary_catheter', 'Temporary Catheter'), ('other', 'Other')], max_length=100),
        ),
        migrations.CreateModel(
            name='LabResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('test_date', models.DateField()),
                ('blood_urea_nitrogen', models.DecimalField(blank=True, decimal_places=2, help_text='BUN mg/dL (normal: 7-20)', max_digits=6, null=True)),
                ('serum_creatinine', models.DecimalField(blank=True, decimal_places=2, help_text='mg/dL (normal: 0.6-1.2)', max_digits=5, null=True)),
                ('pre_dialysis_bun', models.DecimalField(blank=True, decimal_places=2, help_text='BUN before dialysis session mg/dL', max_digits=6, null=True)),
                ('post_dialysis_bun', models.DecimalField(blank=True, decimal_places=2, help_text='BUN after dialysis session mg/dL', max_digits=6, null=True)),
                ('hemoglobin', models.DecimalField(blank=True, decimal_places=1, help_text='Hb g/dL (target: 10-12 for dialysis patients)', max_digits=4, null=True)),
                ('hematocrit', models.DecimalField(blank=True, decimal_places=1, help_text='%', max_digits=4, null=True)),
                ('wbc_count', models.DecimalField(blank=True, decimal_places=2, help_text='x10^3/uL', max_digits=6, null=True)),
                ('platelet_count', models.DecimalField(blank=True, decimal_places=0, help_text='x10^3/uL', max_digits=6, null=True)),
                ('serum_sodium', models.DecimalField(blank=True, decimal_places=1, help_text='mEq/L (135-145)', max_digits=5, null=True)),
                ('serum_potassium', models.DecimalField(blank=True, decimal_places=1, help_text='mEq/L (3.5-5.0, CRITICAL if >6.0)', max_digits=4, null=True)),
                ('serum_calcium', models.DecimalField(blank=True, decimal_places=1, help_text='mg/dL', max_digits=4, null=True)),
                ('serum_phosphorus', models.DecimalField(blank=True, decimal_places=1, help_text='mg/dL', max_digits=4, null=True)),
                ('serum_bicarbonate', models.DecimalField(blank=True, decimal_places=1, help_text='mEq/L', max_digits=4, null=True)),
                ('serum_ferritin', models.DecimalField(blank=True, decimal_places=1, help_text='ng/mL (target: 200-500 for dialysis)', max_digits=7, null=True)),
                ('transferrin_saturation', models.DecimalField(blank=True, decimal_places=1, help_text='TSAT percent (target: 20-50%)', max_digits=4, null=True)),
                ('serum_albumin', models.DecimalField(blank=True, decimal_places=1, help_text='g/dL (target: >=3.5)', max_digits=3, null=True)),
                ('pth', models.DecimalField(blank=True, decimal_places=1, help_text='Parathyroid Hormone pg/mL', max_digits=7, null=True)),
                ('hbsag', models.CharField(blank=True, help_text='Hepatitis B surface antigen', max_length=20)),
                ('anti_hcv', models.CharField(blank=True, help_text='Hepatitis C antibody', max_length=20)),
                ('hiv', models.CharField(blank=True, help_text='HIV test result', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('is_critical', models.BooleanField(default=False, help_text='Flag if any value is critically abnormal')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('ordered_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lab_orders', to=settings.AUTH_USER_MODEL)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lab_results', to='patients.patient')),
            ],
            options={
                'ordering': ['-test_date'],
            },
        ),
        migrations.CreateModel(
            name='DialysisPrescription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_duration_minutes', models.IntegerField(default=240, help_text='Target session duration in minutes (typically 180-300)')),
                ('frequency', models.CharField(choices=[('2_per_week', '2 times per week'), ('3_per_week', '3 times per week'), ('4_per_week', '4 times per week'), ('daily', 'Daily'), ('as_needed', 'As needed')], default='3_per_week', max_length=20)),
                ('target_blood_flow_rate', models.IntegerField(default=300, help_text='Target blood flow rate ml/min (200-500)')),
                ('target_dialysate_flow_rate', models.IntegerField(default=500, help_text='Target dialysate flow rate ml/min (300-800)')),
                ('dialyzer_type', models.CharField(choices=[('low_flux', 'Low Flux'), ('high_flux', 'High Flux'), ('super_flux', 'Super High Flux')], default='high_flux', max_length=50)),
                ('dialyzer_model', models.CharField(blank=True, help_text='Specific dialyzer model e.g. FX80, Polyflux 170H', max_length=100)),
                ('heparin_dose', models.DecimalField(blank=True, decimal_places=2, help_text='Heparin dose in Units', max_digits=6, null=True)),
                ('heparin_frequency', models.CharField(blank=True, default='Loading + maintenance', max_length=100)),
                ('target_dry_weight', models.DecimalField(blank=True, decimal_places=2, help_text='Target dry weight in kg', max_digits=5, null=True)),
                ('target_uf_volume', models.DecimalField(blank=True, decimal_places=2, help_text='Target UF volume in liters', max_digits=4, null=True)),
                ('target_ktv', models.DecimalField(blank=True, decimal_places=2, help_text='Target Kt/V (should be >=1.2)', max_digits=3, null=True)),
                ('dialysate_sodium', models.IntegerField(default=140, help_text='Sodium mEq/L (135-145)')),
                ('dialysate_potassium', models.DecimalField(decimal_places=1, default=2.0, help_text='Potassium mEq/L (1-4)', max_digits=3)),
                ('dialysate_calcium', models.DecimalField(decimal_places=1, default=2.5, help_text='Calcium mEq/L (2.5-3.5)', max_digits=3)),
                ('dialysate_bicarbonate', models.IntegerField(default=35, help_text='Bicarbonate mEq/L (32-40)')),
                ('epo_dose', models.CharField(blank=True, help_text='EPO/ESA dose if prescribed', max_length=100)),
                ('iron_dose', models.CharField(blank=True, help_text='IV Iron dose if prescribed', max_length=100)),
                ('additional_medications', models.TextField(blank=True, help_text='Other medications to give during session')),
                ('special_instructions', models.TextField(blank=True, help_text='Any special instructions for nursing staff')),
                ('is_active', models.BooleanField(default=True, help_text='Only one active prescription per patient')),
                ('effective_date', models.DateField(help_text='Date this prescription becomes effective')),
                ('expiry_date', models.DateField(blank=True, help_text='Review/expiry date', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prescriptions', to='patients.patient')),
                ('prescribed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='prescriptions_written', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
