# Generated by Django 4.2.7 on 2026-01-22 10:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('patients', '0002_patient_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='SMSTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('notification_type', models.CharField(choices=[('appointment_confirmation', 'Appointment Confirmation'), ('appointment_reminder', 'Appointment Reminder'), ('queue_status', 'Queue Status Update'), ('session_start', 'Session Started'), ('session_complete', 'Session Completed'), ('payment_confirmation', 'Payment Confirmation'), ('bill_due', 'Bill Due Reminder'), ('emergency_alert', 'Emergency Alert'), ('general', 'General Notification')], max_length=50)),
                ('template_text', models.TextField(help_text='Use {placeholders} for dynamic content. E.g., {patient_name}, {appointment_date}')),
                ('is_active', models.BooleanField(default=True)),
                ('language', models.CharField(default='en', max_length=10)),
                ('dlt_template_id', models.CharField(blank=True, help_text='DLT Template ID for India (required for MSG91)', max_length=50, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'SMS Template',
                'verbose_name_plural': 'SMS Templates',
                'ordering': ['notification_type', 'name'],
            },
        ),
        migrations.CreateModel(
            name='NotificationPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sms_enabled', models.BooleanField(default=True)),
                ('appointment_reminders', models.BooleanField(default=True)),
                ('queue_updates', models.BooleanField(default=True)),
                ('session_updates', models.BooleanField(default=True)),
                ('payment_notifications', models.BooleanField(default=True)),
                ('bill_reminders', models.BooleanField(default=True)),
                ('reminder_hours_before', models.IntegerField(default=24, help_text='Hours before appointment to send reminder')),
                ('preferred_language', models.CharField(choices=[('en', 'English'), ('hi', 'Hindi')], default='en', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('patient', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='notification_preferences', to='patients.patient')),
            ],
            options={
                'verbose_name': 'Notification Preference',
                'verbose_name_plural': 'Notification Preferences',
            },
        ),
        migrations.CreateModel(
            name='SMSNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(max_length=15)),
                ('message', models.TextField()),
                ('notification_type', models.CharField(choices=[('appointment_confirmation', 'Appointment Confirmation'), ('appointment_reminder', 'Appointment Reminder'), ('queue_status', 'Queue Status Update'), ('session_start', 'Session Started'), ('session_complete', 'Session Completed'), ('payment_confirmation', 'Payment Confirmation'), ('bill_due', 'Bill Due Reminder'), ('emergency_alert', 'Emergency Alert'), ('general', 'General Notification')], default='general', max_length=50)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('sent', 'Sent'), ('failed', 'Failed'), ('delivered', 'Delivered')], default='pending', max_length=20)),
                ('provider', models.CharField(default='MSG91', help_text='SMS provider used (MSG91, Twilio, etc.)', max_length=20)),
                ('provider_message_id', models.CharField(blank=True, help_text='Message ID from SMS provider', max_length=100, null=True)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('retry_count', models.IntegerField(default=0)),
                ('metadata', models.JSONField(blank=True, help_text='Additional data (appointment_id, bill_id, etc.)', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('delivered_at', models.DateTimeField(blank=True, null=True)),
                ('patient', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sms_notifications', to='patients.patient')),
            ],
            options={
                'verbose_name': 'SMS Notification',
                'verbose_name_plural': 'SMS Notifications',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['-created_at'], name='notificatio_created_f04ebb_idx'), models.Index(fields=['status'], name='notificatio_status_c4b476_idx'), models.Index(fields=['notification_type'], name='notificatio_notific_e587c2_idx'), models.Index(fields=['phone_number'], name='notificatio_phone_n_dc8b60_idx')],
            },
        ),
    ]
