# Generated by Django 4.2.7 on 2026-01-22 11:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notificationpreference',
            name='patient',
        ),
        migrations.RemoveField(
            model_name='smsnotification',
            name='patient',
        ),
        migrations.DeleteModel(
            name='SMSTemplate',
        ),
        migrations.DeleteModel(
            name='NotificationPreference',
        ),
        migrations.DeleteModel(
            name='SMSNotification',
        ),
    ]
