# Generated by Django 4.2.7 on 2026-01-08 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0002_payment_gateway_response_payment_processing_fee'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='payment_method',
            field=models.CharField(choices=[('cash', 'Cash'), ('upi', 'UPI/Scanner (PhonePe/GPay/Paytm)')], max_length=20),
        ),
    ]
