# Generated by Django 4.2.7 on 2025-10-16 18:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CleaningLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cleaning_type', models.CharField(choices=[('disinfection', 'Disinfection'), ('sterilization', 'Sterilization'), ('sanitization', 'Sanitization')], max_length=20)),
                ('cleaning_date', models.DateTimeField(auto_now_add=True)),
                ('cleaning_agent', models.CharField(max_length=100)),
                ('concentration', models.CharField(blank=True, max_length=50)),
                ('contact_time', models.IntegerField(help_text='Contact time in minutes')),
                ('bacterial_count_before', models.IntegerField(blank=True, null=True)),
                ('bacterial_count_after', models.IntegerField(blank=True, null=True)),
                ('endotoxin_level', models.DecimalField(blank=True, decimal_places=3, max_digits=6, null=True)),
                ('notes', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['-cleaning_date'],
            },
        ),
        migrations.CreateModel(
            name='DialysisMachine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('machine_id', models.CharField(max_length=20, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('machine_type', models.CharField(choices=[('hemodialysis', 'Hemodialysis'), ('peritoneal', 'Peritoneal'), ('hdf', 'HDF')], default='hemodialysis', max_length=20)),
                ('manufacturer', models.CharField(max_length=100)),
                ('model', models.CharField(max_length=100)),
                ('serial_number', models.CharField(max_length=100, unique=True)),
                ('status', models.CharField(choices=[('available', '🟢 Available'), ('in_use', '🔵 In Use'), ('maintenance', '🟠 Maintenance'), ('cleaning', '🟡 Cleaning'), ('out_of_service', '🔴 Out of Service')], default='available', max_length=20)),
                ('current_session_start', models.DateTimeField(blank=True, null=True)),
                ('purchase_date', models.DateField()),
                ('warranty_expiry', models.DateField(blank=True, null=True)),
                ('last_maintenance_date', models.DateField(blank=True, null=True)),
                ('next_maintenance_date', models.DateField(blank=True, null=True)),
                ('maintenance_interval_days', models.IntegerField(default=90)),
                ('total_sessions', models.IntegerField(default=0)),
                ('total_operating_hours', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('water_quality_required', models.BooleanField(default=True)),
                ('power_requirements', models.CharField(blank=True, max_length=100)),
                ('weight', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('dimensions', models.CharField(blank=True, max_length=100)),
                ('notes', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['machine_id'],
            },
        ),
        migrations.CreateModel(
            name='MaintenanceLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('maintenance_type', models.CharField(choices=[('routine', 'Routine Maintenance'), ('repair', 'Repair'), ('calibration', 'Calibration'), ('inspection', 'Inspection')], max_length=20)),
                ('maintenance_date', models.DateField()),
                ('next_maintenance_date', models.DateField()),
                ('description', models.TextField()),
                ('parts_replaced', models.TextField(blank=True)),
                ('cost', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('blood_leak_test', models.BooleanField(default=True)),
                ('pressure_test', models.BooleanField(default=True)),
                ('conductivity_test', models.BooleanField(default=True)),
                ('temperature_test', models.BooleanField(default=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('machine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='maintenance_logs', to='machines.dialysismachine')),
            ],
            options={
                'ordering': ['-maintenance_date'],
            },
        ),
    ]
