# Generated by Django 4.2.7 on 2025-10-16 18:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('appointments', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='QueueSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('max_emergency_cases', models.IntegerField(default=3)),
                ('max_wait_time_emergency', models.IntegerField(default=10)),
                ('max_wait_time_scheduled', models.IntegerField(default=45)),
                ('max_wait_time_walk_in', models.IntegerField(default=90)),
                ('auto_assign_machines', models.BooleanField(default=True)),
                ('notify_long_waits', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name_plural': 'Queue Settings',
            },
        ),
        migrations.CreateModel(
            name='Queue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('queue_number', models.CharField(max_length=10, unique=True)),
                ('priority', models.CharField(choices=[('emergency', 'Emergency'), ('scheduled', 'Scheduled'), ('walk_in', 'Walk-in')], default='scheduled', max_length=20)),
                ('status', models.CharField(choices=[('waiting', '🟡 Waiting'), ('in_progress', '🟢 In Progress'), ('completed', '✅ Completed'), ('cancelled', '❌ Cancelled')], default='waiting', max_length=20)),
                ('check_in_time', models.DateTimeField(auto_now_add=True)),
                ('estimated_wait_time', models.IntegerField(default=0, help_text='Estimated wait time in minutes')),
                ('actual_start_time', models.DateTimeField(blank=True, null=True)),
                ('actual_end_time', models.DateTimeField(blank=True, null=True)),
                ('assigned_machine', models.CharField(blank=True, max_length=50)),
                ('blood_pressure', models.CharField(blank=True, max_length=20)),
                ('weight_before', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('weight_after', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('appointment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='appointments.appointment')),
            ],
            options={
                'ordering': ['-priority', 'check_in_time'],
            },
        ),
    ]
