# Generated by Django 4.2.7 on 2026-01-05 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dialysis_queue', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='queue',
            name='queue_number',
            field=models.CharField(blank=True, max_length=10, null=True, unique=True),
        ),
    ]
