# Generated by Django 4.2.7 on 2026-01-06 10:16

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('patients', '0001_initial'),
        ('dialysis_queue', '0003_alter_queue_queue_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='DialysisSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pre_bp_systolic', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(50), django.core.validators.MaxValueValidator(250)])),
                ('pre_bp_diastolic', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(30), django.core.validators.MaxValueValidator(150)])),
                ('pre_heart_rate', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(40), django.core.validators.MaxValueValidator(200)])),
                ('pre_temperature', models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True)),
                ('pre_oxygen_saturation', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(70), django.core.validators.MaxValueValidator(100)])),
                ('post_bp_systolic', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(50), django.core.validators.MaxValueValidator(250)])),
                ('post_bp_diastolic', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(30), django.core.validators.MaxValueValidator(150)])),
                ('post_heart_rate', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(40), django.core.validators.MaxValueValidator(200)])),
                ('post_temperature', models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True)),
                ('post_oxygen_saturation', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(70), django.core.validators.MaxValueValidator(100)])),
                ('blood_flow_rate', models.IntegerField(blank=True, help_text='ml/min', null=True)),
                ('dialysate_flow_rate', models.IntegerField(blank=True, help_text='ml/min', null=True)),
                ('ultrafiltration_volume', models.DecimalField(blank=True, decimal_places=2, help_text='Liters', max_digits=5, null=True)),
                ('heparin_dose', models.DecimalField(blank=True, decimal_places=2, help_text='Units', max_digits=6, null=True)),
                ('medications', models.TextField(blank=True, help_text='List medications given during session')),
                ('complications', models.TextField(blank=True, help_text='Any complications during session')),
                ('adverse_events', models.TextField(blank=True, help_text='Adverse events if any')),
                ('nurse_notes', models.TextField(blank=True)),
                ('doctor_notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('attending_doctor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='doctor_sessions', to=settings.AUTH_USER_MODEL)),
                ('attending_nurse', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='nurse_sessions', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_sessions', to=settings.AUTH_USER_MODEL)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dialysis_sessions', to='patients.patient')),
                ('queue', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='session_details', to='dialysis_queue.queue')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
