# Generated by Django 4.2.7 on 2026-01-08 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dialysis_queue', '0004_dialysissession'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dialysissession',
            name='post_bp_diastolic',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='dialysissession',
            name='post_bp_systolic',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='dialysissession',
            name='post_heart_rate',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='dialysissession',
            name='post_oxygen_saturation',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='dialysissession',
            name='pre_bp_diastolic',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='dialysissession',
            name='pre_bp_systolic',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='dialysissession',
            name='pre_heart_rate',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='dialysissession',
            name='pre_oxygen_saturation',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
