# Generated by Django 4.2.7 on 2026-04-22 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dialysis_queue', '0005_alter_dialysissession_post_bp_diastolic_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='queuesettings',
            name='afternoon_shift_end',
            field=models.TimeField(default='18:00', help_text='Afternoon shift end time'),
        ),
        migrations.AddField(
            model_name='queuesettings',
            name='afternoon_shift_start',
            field=models.TimeField(default='12:00', help_text='Afternoon shift start time'),
        ),
        migrations.AddField(
            model_name='queuesettings',
            name='evening_shift_end',
            field=models.TimeField(default='22:00', help_text='Evening shift end time'),
        ),
        migrations.AddField(
            model_name='queuesettings',
            name='evening_shift_start',
            field=models.TimeField(default='18:00', help_text='Evening shift start time'),
        ),
        migrations.AddField(
            model_name='queuesettings',
            name='max_patients_per_shift',
            field=models.IntegerField(default=6, help_text='Max patients per shift (usually = total machines)'),
        ),
        migrations.AddField(
            model_name='queuesettings',
            name='max_session_duration_minutes',
            field=models.IntegerField(default=300, help_text='Alert if session exceeds this (in minutes)'),
        ),
        migrations.AddField(
            model_name='queuesettings',
            name='min_session_duration_minutes',
            field=models.IntegerField(default=60, help_text='Alert if session is shorter than this'),
        ),
        migrations.AddField(
            model_name='queuesettings',
            name='morning_shift_end',
            field=models.TimeField(default='12:00', help_text='Morning shift end time'),
        ),
        migrations.AddField(
            model_name='queuesettings',
            name='morning_shift_start',
            field=models.TimeField(default='06:00', help_text='Morning shift start time'),
        ),
        migrations.AddField(
            model_name='queuesettings',
            name='session_duration_hours',
            field=models.IntegerField(default=4, help_text='Standard session duration in hours'),
        ),
        migrations.AddField(
            model_name='queuesettings',
            name='total_machines',
            field=models.IntegerField(default=6, help_text='Total dialysis machines in center'),
        ),
    ]
