# Generated by Django 4.2.7 on 2026-01-23 13:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('two_factor', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='backupcode',
            options={'ordering': ['-created_at']},
        ),
        migrations.CreateModel(
            name='TwoFactorReminder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_reminder_shown', models.DateTimeField(blank=True, null=True)),
                ('reminder_skip_count', models.IntegerField(default=0)),
                ('logout_count', models.IntegerField(default=0)),
                ('hours_between_reminders', models.IntegerField(default=24)),
                ('logouts_before_reminder', models.IntegerField(default=5)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='two_factor_reminder', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Two-Factor Reminder',
                'verbose_name_plural': 'Two-Factor Reminders',
            },
        ),
    ]
