# Generated by Django 4.2.7 on 2026-01-23 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('two_factor', '0002_alter_backupcode_options_twofactorreminder'),
    ]

    operations = [
        migrations.AddField(
            model_name='twofactorreminder',
            name='grace_logins_allowed',
            field=models.IntegerField(default=3),
        ),
        migrations.AddField(
            model_name='twofactorreminder',
            name='grace_logins_remaining',
            field=models.IntegerField(default=0),
        ),
    ]
