# Generated by Django 4.2.7 on 2026-01-24 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('two_factor', '0003_twofactorreminder_grace_logins_allowed_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='twofactorreminder',
            old_name='logout_count',
            new_name='login_count',
        ),
        migrations.RemoveField(
            model_name='twofactorreminder',
            name='logouts_before_reminder',
        ),
        migrations.AddField(
            model_name='twofactorreminder',
            name='logins_before_reminder',
            field=models.IntegerField(default=3),
        ),
    ]
