/**
 * pdfDownload.js — Client-side PDF generation utilities
 * Uses jsPDF + jspdf-autotable to generate professional PDFs in the browser.
 *
 * IMPORTANT: Use named import for autoTable to avoid Vite HMR issues.
 * Call autoTable(doc, options) — NOT doc.autoTable(options).
 */

import jsPDF from 'jspdf';
import autoTable from 'jspdf-autotable'; // named import — patches via function call

const BRAND_COLOR  = [14, 116, 144];   // cyan-700
const GREEN_COLOR  = [5, 150, 105];    // emerald-600
const DARK_COLOR   = [31, 41, 55];     // gray-800
const LIGHT_GRAY   = [243, 244, 246];  // gray-100
const WHITE        = [255, 255, 255];

/** Format currency safely — ₹ glyph not in default jsPDF font */
function cur(amount) {
    return `Rs. ${Number(amount || 0).toFixed(2)}`;
}

/* ─── Shared header ─────────────────────────────────────────────────────── */
function _addHeader(doc, title, subtitle = '') {
    const pageW = doc.internal.pageSize.getWidth();
    doc.setFillColor(...BRAND_COLOR);
    doc.rect(0, 0, pageW, 30, 'F');

    doc.setTextColor(...WHITE);
    doc.setFontSize(18);
    doc.setFont('helvetica', 'bold');
    doc.text('DialysisTrack', 14, 12);

    doc.setFontSize(8);
    doc.setFont('helvetica', 'normal');
    doc.text('Dialysis Management System', 14, 21);

    doc.setFontSize(13);
    doc.setFont('helvetica', 'bold');
    doc.text(title, pageW - 14, 13, { align: 'right' });

    if (subtitle) {
        doc.setFontSize(8);
        doc.setFont('helvetica', 'normal');
        doc.text(subtitle, pageW - 14, 22, { align: 'right' });
    }

    doc.setDrawColor(...GREEN_COLOR);
    doc.setLineWidth(1.5);
    doc.line(0, 30, pageW, 30);
}

/* ─── Shared footer ─────────────────────────────────────────────────────── */
function _addFooter(doc) {
    const pageH   = doc.internal.pageSize.getHeight();
    const pageW   = doc.internal.pageSize.getWidth();
    const total   = doc.internal.getNumberOfPages();
    for (let i = 1; i <= total; i++) {
        doc.setPage(i);
        doc.setDrawColor(229, 231, 235);
        doc.setLineWidth(0.5);
        doc.line(14, pageH - 14, pageW - 14, pageH - 14);
        doc.setFontSize(7.5);
        doc.setTextColor(156, 163, 175);
        doc.text('Generated by DialysisTrack System', 14, pageH - 6);
        doc.text(`Page ${i} of ${total}`, pageW - 14, pageH - 6, { align: 'right' });
    }
}

/* ─── Section label helper ─────────────────────────────────────────────── */
function _sectionLabel(doc, label, y) {
    doc.setFont('helvetica', 'bold');
    doc.setFontSize(10.5);
    doc.setTextColor(...BRAND_COLOR);
    doc.text(label, 14, y);
    return y + 6;
}

/* ─── Shorthand: run autoTable and return finalY ───────────────────────── */
function _table(doc, opts) {
    autoTable(doc, opts);
    return doc.lastAutoTable.finalY;
}


// ─────────────────────────────────────────────────────────────────────────────
// 1. PAYMENT RECEIPT PDF
// ─────────────────────────────────────────────────────────────────────────────
export function downloadReceiptPDF(bill, patient = {}) {
    const doc = new jsPDF({ unit: 'pt', format: 'a4' });
    const now = new Date().toLocaleString('en-IN', {
        day: '2-digit', month: 'short', year: 'numeric',
        hour: '2-digit', minute: '2-digit'
    });

    _addHeader(doc, 'PAYMENT RECEIPT', `Generated: ${now}`);

    const pageW = doc.internal.pageSize.getWidth();
    let y = 40;

    /* ── Patient + Bill info cards ── */
    const halfW = (pageW - 28) / 2 - 4;

    doc.setFillColor(...LIGHT_GRAY);
    doc.roundedRect(14, y, halfW, 68, 3, 3, 'F');
    doc.setFillColor(230, 247, 255);
    doc.roundedRect(18 + halfW, y, halfW, 68, 3, 3, 'F');

    // Patient block
    doc.setFont('helvetica', 'bold'); doc.setFontSize(9); doc.setTextColor(...BRAND_COLOR);
    doc.text('PATIENT', 20, y + 12);
    doc.setFont('helvetica', 'normal'); doc.setTextColor(...DARK_COLOR); doc.setFontSize(8.5);
    doc.text(`Name    : ${patient.name || 'N/A'}`,       20, y + 26);
    doc.text(`ID      : ${patient.patient_id || 'N/A'}`, 20, y + 39);
    doc.text(`Phone   : ${patient.phone || 'N/A'}`,      20, y + 52);

    // Bill block
    const rx = 22 + halfW;
    doc.setFont('helvetica', 'bold'); doc.setFontSize(9); doc.setTextColor(...BRAND_COLOR);
    doc.text('BILL', rx, y + 12);
    doc.setFont('helvetica', 'normal'); doc.setTextColor(...DARK_COLOR); doc.setFontSize(8.5);
    doc.text(`Bill #  : ${bill.bill_number || bill.id || 'N/A'}`,         rx, y + 26);
    doc.text(`Date    : ${bill.bill_date || bill.created_at || now}`,      rx, y + 39);
    doc.text(`Status  : ${(bill.payment_status || bill.status || 'N/A').toUpperCase()}`, rx, y + 52);

    y += 80;

    /* ── Charges table ── */
    y = _sectionLabel(doc, 'Charges Breakdown', y);
    const chargesRows = [];
    if (bill.session_cost     !== undefined) chargesRows.push(['Dialysis Session',  cur(bill.session_cost)]);
    if (bill.medicines_cost   !== undefined) chargesRows.push(['Medicines',         cur(bill.medicines_cost)]);
    if (bill.consultation_fee !== undefined) chargesRows.push(['Consultation Fee',  cur(bill.consultation_fee)]);
    if (bill.other_charges    !== undefined) chargesRows.push(['Other Charges',     cur(bill.other_charges)]);
    if (chargesRows.length === 0)             chargesRows.push(['Services',          cur(bill.total_amount)]);
    if (bill.subtotal !== undefined)          chargesRows.push(['Subtotal',          cur(bill.subtotal)]);
    if (bill.gst_amount !== undefined)        chargesRows.push(['GST (18%)',         cur(bill.gst_amount)]);
    if (Number(bill.discount) > 0)            chargesRows.push(['Discount',          `- ${cur(bill.discount)}`]);

    y = _table(doc, {
        startY: y,
        head: [['Description', 'Amount']],
        body: chargesRows,
        columnStyles: { 1: { halign: 'right' } },
        headStyles: { fillColor: BRAND_COLOR, textColor: WHITE, fontStyle: 'bold', fontSize: 9 },
        bodyStyles: { fontSize: 8.5, textColor: DARK_COLOR },
        alternateRowStyles: { fillColor: [249, 250, 251] },
        margin: { left: 14, right: 14 },
        tableWidth: pageW - 28,
    }) + 10;

    /* ── Summary box ── */
    const summaryRows = [
        ['Total Amount',  cur(bill.total_amount)],
        ['Paid Amount',   cur(bill.paid_amount)],
        [Number(bill.balance_amount || 0) > 0 ? 'Balance Due' : 'Fully Paid', cur(bill.balance_amount)],
    ];
    y = _table(doc, {
        startY: y,
        body: summaryRows,
        columnStyles: {
            0: { fontStyle: 'bold', textColor: DARK_COLOR },
            1: { halign: 'right', fontStyle: 'bold' },
        },
        bodyStyles: { fontSize: 9.5 },
        alternateRowStyles: { fillColor: WHITE },
        margin: { left: pageW - 220, right: 14 },
        tableWidth: 210,
    }) + 14;

    /* ── Payment history ── */
    const payments = bill.payments || [];
    if (payments.length > 0) {
        y = _sectionLabel(doc, 'Payment History', y);
        y = _table(doc, {
            startY: y,
            head: [['Date', 'Method', 'Amount', 'Transaction ID']],
            body: payments.map(p => [
                p.payment_date || 'N/A',
                (p.payment_mode || p.payment_method || 'N/A').toUpperCase(),
                cur(p.amount),
                p.transaction_id || '—',
            ]),
            headStyles: { fillColor: GREEN_COLOR, textColor: WHITE, fontStyle: 'bold', fontSize: 8.5 },
            bodyStyles: { fontSize: 8, textColor: DARK_COLOR },
            alternateRowStyles: { fillColor: [240, 253, 244] },
            margin: { left: 14, right: 14 },
            tableWidth: pageW - 28,
            columnStyles: { 2: { halign: 'right' } },
        }) + 10;
    }

    /* ── PAID watermark ── */
    if (Number(bill.balance_amount || 0) === 0) {
        doc.setFontSize(60);
        doc.setFont('helvetica', 'bold');
        doc.setTextColor(5, 150, 105);
        try {
            doc.setGState(new doc.GState({ opacity: 0.08 }));
        } catch (_) { /* GState unsupported — skip opacity */ }
        doc.text('PAID', pageW / 2, 500, { align: 'center', angle: -30 });
        try { doc.setGState(new doc.GState({ opacity: 1 })); } catch (_) {}
    }

    _addFooter(doc);
    doc.save(`Receipt_${bill.bill_number || bill.id || 'bill'}.pdf`);
}


// ─────────────────────────────────────────────────────────────────────────────
// 2. SESSION DETAILS PDF
// ─────────────────────────────────────────────────────────────────────────────
export function downloadSessionPDF(session, patient = {}) {
    const doc = new jsPDF({ unit: 'pt', format: 'a4' });
    const now = new Date().toLocaleString('en-IN', {
        day: '2-digit', month: 'short', year: 'numeric',
        hour: '2-digit', minute: '2-digit'
    });
    const sessionDate = session.date
        ? new Date(session.date).toLocaleDateString('en-IN', {
            day: '2-digit', month: 'short', year: 'numeric'
          })
        : 'N/A';

    _addHeader(doc, 'SESSION SUMMARY', `Session: ${sessionDate}`);

    const pageW = doc.internal.pageSize.getWidth();
    let y = 40;

    /* ── Patient info banner ── */
    doc.setFillColor(...LIGHT_GRAY);
    doc.roundedRect(14, y, pageW - 28, 58, 3, 3, 'F');
    doc.setFont('helvetica', 'bold'); doc.setFontSize(9); doc.setTextColor(...BRAND_COLOR);
    doc.text('PATIENT INFORMATION', 20, y + 13);
    doc.setFont('helvetica', 'normal'); doc.setTextColor(...DARK_COLOR); doc.setFontSize(8.5);
    doc.text(`Name       : ${patient.name || 'N/A'}`,           20, y + 27);
    doc.text(`Patient ID : ${patient.patient_id || 'N/A'}`,     20, y + 40);
    doc.text(`Blood Type : ${patient.blood_type || 'N/A'}`,     20, y + 53);

    const col2 = pageW / 2 + 10;
    doc.text(`Session ID : #${session.id || 'N/A'}`,            col2, y + 27);
    doc.text(`Machine    : ${session.machine_number || 'N/A'}`, col2, y + 40);
    doc.text(`Duration   : ${session.duration_minutes || session.duration || 'N/A'} min`, col2, y + 53);
    y += 70;

    /* ── Vitals comparison ── */
    y = _sectionLabel(doc, 'Vital Signs (Pre vs Post)', y);
    y = _table(doc, {
        startY: y,
        head: [['Parameter', 'Pre-Dialysis', 'Post-Dialysis', 'Change']],
        body: [
            [
                'Weight (kg)',
                String(session.pre_dialysis_weight  || session.pre_weight  || 'N/A'),
                String(session.post_dialysis_weight || session.post_weight || 'N/A'),
                (session.pre_dialysis_weight && session.post_dialysis_weight)
                    ? `${(Number(session.pre_dialysis_weight) - Number(session.post_dialysis_weight)).toFixed(2)} kg lost`
                    : '—',
            ],
            [
                'Blood Pressure (mmHg)',
                session.pre_bp_systolic  ? `${session.pre_bp_systolic}/${session.pre_bp_diastolic}`   : 'N/A',
                session.post_bp_systolic ? `${session.post_bp_systolic}/${session.post_bp_diastolic}` : 'N/A',
                '—',
            ],
            ['Heart Rate (bpm)',    String(session.pre_heart_rate  || 'N/A'), String(session.post_heart_rate  || 'N/A'), '—'],
            ['Temperature (deg F)', String(session.pre_temperature || 'N/A'), String(session.post_temperature || 'N/A'), '—'],
        ],
        headStyles: { fillColor: BRAND_COLOR, textColor: WHITE, fontStyle: 'bold', fontSize: 9 },
        bodyStyles: { fontSize: 8.5, textColor: DARK_COLOR },
        alternateRowStyles: { fillColor: [239, 246, 255] },
        margin: { left: 14, right: 14 },
        tableWidth: pageW - 28,
        columnStyles: {
            0: { fontStyle: 'bold', cellWidth: 140 },
            3: { textColor: [5, 150, 105], fontStyle: 'italic' },
        },
    }) + 14;

    /* ── Parameters ── */
    y = _sectionLabel(doc, 'Dialysis Parameters', y);
    y = _table(doc, {
        startY: y,
        head: [['Parameter', 'Value']],
        body: [
            ['Session Duration',         `${session.duration_minutes || session.duration || 'N/A'} minutes`],
            ['Ultrafiltration Volume',    `${session.ultrafiltration_volume || 'N/A'} L`],
            ['Machine Number',             session.machine_number || 'N/A'],
            ['Session Date',               sessionDate],
            ['Session Time',               session.time
                ? new Date(`1970-01-01T${session.time}`).toLocaleTimeString('en-IN', { hour: '2-digit', minute: '2-digit' })
                : 'N/A'],
        ],
        headStyles: { fillColor: GREEN_COLOR, textColor: WHITE, fontStyle: 'bold', fontSize: 9 },
        bodyStyles: { fontSize: 8.5, textColor: DARK_COLOR },
        alternateRowStyles: { fillColor: [240, 253, 244] },
        margin: { left: 14, right: 14 },
        tableWidth: pageW - 28,
        columnStyles: { 0: { fontStyle: 'bold', cellWidth: 200 } },
    }) + 14;

    /* ── Complications / Notes ── */
    const hasComps = session.complications && String(session.complications).trim();
    const hasNotes = session.notes        && String(session.notes).trim();
    if (hasComps || hasNotes) {
        y = _sectionLabel(doc, 'Clinical Notes', y) + 4;
        if (hasComps) {
            doc.setFillColor(254, 243, 199);
            doc.roundedRect(14, y, pageW - 28, 28, 3, 3, 'F');
            doc.setFont('helvetica', 'bold'); doc.setFontSize(8.5); doc.setTextColor(146, 64, 14);
            doc.text('Complications:', 20, y + 11);
            doc.setFont('helvetica', 'normal'); doc.setTextColor(...DARK_COLOR);
            doc.text(String(session.complications), 110, y + 11, { maxWidth: pageW - 130 });
            y += 34;
        }
        if (hasNotes) {
            doc.setFillColor(239, 246, 255);
            doc.roundedRect(14, y, pageW - 28, 28, 3, 3, 'F');
            doc.setFont('helvetica', 'bold'); doc.setFontSize(8.5); doc.setTextColor(30, 64, 175);
            doc.text('Notes:', 20, y + 11);
            doc.setFont('helvetica', 'normal'); doc.setTextColor(...DARK_COLOR);
            doc.text(String(session.notes), 70, y + 11, { maxWidth: pageW - 90 });
            y += 34;
        }
    }

    doc.setFontSize(7.5);
    doc.setTextColor(156, 163, 175);
    doc.text(`Report generated on ${now}`, 14, y + 14);

    _addFooter(doc);
    doc.save(`Session_${session.id || 'summary'}_${sessionDate.replace(/ /g, '-')}.pdf`);
}


// ─────────────────────────────────────────────────────────────────────────────
// 3. APPOINTMENT CONFIRMATION PDF
// ─────────────────────────────────────────────────────────────────────────────
export function downloadAppointmentPDF(appointment, patient = {}) {
    const doc = new jsPDF({ unit: 'pt', format: 'a4' });
    const now = new Date().toLocaleString('en-IN', {
        day: '2-digit', month: 'short', year: 'numeric',
        hour: '2-digit', minute: '2-digit'
    });
    const aptDate = appointment.appointment_date
        ? new Date(appointment.appointment_date).toLocaleDateString('en-IN', {
            weekday: 'long', day: '2-digit', month: 'long', year: 'numeric'
          })
        : 'N/A';

    _addHeader(doc, 'APPOINTMENT CONFIRMATION', `Generated: ${now}`);

    const pageW = doc.internal.pageSize.getWidth();
    let y = 46;

    /* ── Confirmed banner ── */
    doc.setFillColor(209, 250, 229);
    doc.roundedRect(14, y, pageW - 28, 36, 5, 5, 'F');
    doc.setFont('helvetica', 'bold'); doc.setFontSize(12); doc.setTextColor(...GREEN_COLOR);
    doc.text('Appointment Confirmed', pageW / 2, y + 22, { align: 'center' });
    y += 48;

    y = _table(doc, {
        startY: y,
        body: [
            ['Patient Name',      patient.name        || 'N/A'],
            ['Patient ID',        patient.patient_id  || 'N/A'],
            ['Appointment Date',  aptDate],
            ['Shift',             ((appointment.shift || 'N/A').charAt(0).toUpperCase() + (appointment.shift || '').slice(1))],
            ['Scheduled Time',    appointment.scheduled_time  || 'N/A'],
            ['Machine',           appointment.machine_number  || 'To be assigned'],
            ['Status',            (appointment.status || 'Scheduled').replace('_', ' ').toUpperCase()],
            ['Notes',             appointment.notes || '—'],
        ],
        columnStyles: {
            0: { fontStyle: 'bold', cellWidth: 160, fillColor: LIGHT_GRAY, textColor: DARK_COLOR },
            1: { textColor: DARK_COLOR },
        },
        bodyStyles: { fontSize: 9.5, cellPadding: 9 },
        alternateRowStyles: { fillColor: WHITE },
        margin: { left: 14, right: 14 },
        tableWidth: pageW - 28,
    }) + 18;

    doc.setFontSize(8.5);
    doc.setFont('helvetica', 'italic');
    doc.setTextColor(107, 114, 128);
    doc.text(
        'Please arrive 15 minutes before your scheduled time. Bring this document for check-in.',
        14, y, { maxWidth: pageW - 28 }
    );

    _addFooter(doc);
    doc.save(`Appointment_${appointment.id || 'confirmation'}.pdf`);
}


// ─────────────────────────────────────────────────────────────────────────────
// 4. DIALYSIS PRESCRIPTION PDF
// ─────────────────────────────────────────────────────────────────────────────
export function downloadPrescriptionPDF(prescription, patient = {}) {
    const doc = new jsPDF({ unit: 'pt', format: 'a4' });
    const now = new Date().toLocaleString('en-IN', {
        day: '2-digit', month: 'short', year: 'numeric',
        hour: '2-digit', minute: '2-digit'
    });

    _addHeader(doc, 'DIALYSIS PRESCRIPTION', `Effective: ${prescription.effective_date || 'N/A'}`);

    const pageW = doc.internal.pageSize.getWidth();
    let y = 44;

    /* ── Rx Banner ── */
    doc.setFillColor(239, 246, 255);
    doc.roundedRect(14, y, pageW - 28, 32, 5, 5, 'F');
    doc.setFont('helvetica', 'bold'); doc.setFontSize(14); doc.setTextColor(30, 64, 175);
    doc.text('Rx  DIALYSIS ORDER', pageW / 2, y + 21, { align: 'center' });
    y += 44;

    /* ── Patient Info ── */
    y = _sectionLabel(doc, 'Patient Information', y);
    y = _table(doc, {
        startY: y,
        body: [
            ['Patient Name', patient.name || `${patient.first_name || ''} ${patient.last_name || ''}`.trim() || 'N/A'],
            ['Patient ID', patient.patient_id || 'N/A'],
            ['Blood Type', patient.blood_type || 'N/A'],
            ['Vascular Access', patient.vascular_access || 'N/A'],
            ['Prescribed By', prescription.prescribed_by_name || 'N/A'],
        ],
        columnStyles: {
            0: { fontStyle: 'bold', cellWidth: 160, fillColor: LIGHT_GRAY },
            1: { textColor: DARK_COLOR },
        },
        bodyStyles: { fontSize: 9, cellPadding: 7 },
        alternateRowStyles: { fillColor: WHITE },
        margin: { left: 14, right: 14 },
        tableWidth: pageW - 28,
    }) + 12;

    /* ── Session Parameters ── */
    y = _sectionLabel(doc, 'Session Parameters', y);
    y = _table(doc, {
        startY: y,
        head: [['Parameter', 'Prescribed Value']],
        body: [
            ['Session Duration', `${prescription.session_duration_minutes || 240} minutes`],
            ['Frequency', prescription.frequency_display || prescription.frequency || 'N/A'],
            ['Blood Flow Rate (Qb)', `${prescription.target_blood_flow_rate || 300} ml/min`],
            ['Dialysate Flow Rate (Qd)', `${prescription.target_dialysate_flow_rate || 500} ml/min`],
            ['Dialyzer Type', prescription.dialyzer_type_display || prescription.dialyzer_type || 'N/A'],
            ['Dialyzer Model', prescription.dialyzer_model || 'N/A'],
            ['Target Dry Weight', prescription.target_dry_weight ? `${prescription.target_dry_weight} kg` : 'N/A'],
            ['Target UF Volume', prescription.target_uf_volume ? `${prescription.target_uf_volume} L` : 'N/A'],
            ['Target Kt/V', prescription.target_ktv ? `>= ${prescription.target_ktv}` : '>= 1.2'],
        ],
        headStyles: { fillColor: BRAND_COLOR, textColor: WHITE, fontStyle: 'bold', fontSize: 9 },
        bodyStyles: { fontSize: 8.5, textColor: DARK_COLOR },
        alternateRowStyles: { fillColor: [239, 246, 255] },
        margin: { left: 14, right: 14 },
        tableWidth: pageW - 28,
        columnStyles: { 0: { fontStyle: 'bold', cellWidth: 200 } },
    }) + 12;

    /* ── Anticoagulation ── */
    y = _sectionLabel(doc, 'Anticoagulation', y);
    y = _table(doc, {
        startY: y,
        body: [
            ['Heparin Dose', prescription.heparin_dose ? `${prescription.heparin_dose} Units` : 'N/A'],
            ['Heparin Protocol', prescription.heparin_frequency || 'Loading + maintenance'],
        ],
        columnStyles: {
            0: { fontStyle: 'bold', cellWidth: 200, fillColor: LIGHT_GRAY },
        },
        bodyStyles: { fontSize: 8.5, cellPadding: 7 },
        alternateRowStyles: { fillColor: WHITE },
        margin: { left: 14, right: 14 },
        tableWidth: pageW - 28,
    }) + 12;

    /* ── Dialysate Composition ── */
    y = _sectionLabel(doc, 'Dialysate Composition', y);
    y = _table(doc, {
        startY: y,
        head: [['Electrolyte', 'Concentration']],
        body: [
            ['Sodium (Na+)', `${prescription.dialysate_sodium || 140} mEq/L`],
            ['Potassium (K+)', `${prescription.dialysate_potassium || 2.0} mEq/L`],
            ['Calcium (Ca2+)', `${prescription.dialysate_calcium || 2.5} mEq/L`],
            ['Bicarbonate (HCO3-)', `${prescription.dialysate_bicarbonate || 35} mEq/L`],
        ],
        headStyles: { fillColor: GREEN_COLOR, textColor: WHITE, fontStyle: 'bold', fontSize: 9 },
        bodyStyles: { fontSize: 8.5, textColor: DARK_COLOR },
        alternateRowStyles: { fillColor: [240, 253, 244] },
        margin: { left: 14, right: 14 },
        tableWidth: pageW - 28,
        columnStyles: { 0: { fontStyle: 'bold', cellWidth: 200 } },
    }) + 12;

    /* ── Additional Medications ── */
    const meds = [];
    if (prescription.epo_dose) meds.push(['EPO/ESA', prescription.epo_dose]);
    if (prescription.iron_dose) meds.push(['IV Iron', prescription.iron_dose]);
    if (prescription.additional_medications) meds.push(['Other', prescription.additional_medications]);
    if (meds.length > 0) {
        y = _sectionLabel(doc, 'Additional Medications During Session', y);
        y = _table(doc, {
            startY: y,
            body: meds,
            columnStyles: { 0: { fontStyle: 'bold', cellWidth: 150, fillColor: [254, 243, 199] } },
            bodyStyles: { fontSize: 8.5, cellPadding: 7 },
            margin: { left: 14, right: 14 },
            tableWidth: pageW - 28,
        }) + 12;
    }

    /* ── Special Instructions ── */
    if (prescription.special_instructions) {
        y = _sectionLabel(doc, 'Special Instructions', y);
        doc.setFillColor(254, 243, 199);
        doc.roundedRect(14, y, pageW - 28, 40, 3, 3, 'F');
        doc.setFont('helvetica', 'normal'); doc.setFontSize(9); doc.setTextColor(...DARK_COLOR);
        doc.text(String(prescription.special_instructions), 20, y + 14, { maxWidth: pageW - 40 });
        y += 50;
    }

    /* ── Signature area ── */
    y += 20;
    doc.setDrawColor(200, 200, 200);
    doc.line(pageW - 220, y, pageW - 14, y);
    doc.setFontSize(8); doc.setTextColor(107, 114, 128);
    doc.text('Prescribing Doctor Signature', pageW - 220, y + 12);

    _addFooter(doc);
    doc.save(`Prescription_${patient.patient_id || 'rx'}_${prescription.effective_date || 'latest'}.pdf`);
}


// ─────────────────────────────────────────────────────────────────────────────
// 5. LAB REPORT PDF
// ─────────────────────────────────────────────────────────────────────────────
export function downloadLabReportPDF(labResult, patient = {}) {
    const doc = new jsPDF({ unit: 'pt', format: 'a4' });
    const now = new Date().toLocaleString('en-IN', {
        day: '2-digit', month: 'short', year: 'numeric',
        hour: '2-digit', minute: '2-digit'
    });

    _addHeader(doc, 'LABORATORY REPORT', `Test Date: ${labResult.test_date || 'N/A'}`);

    const pageW = doc.internal.pageSize.getWidth();
    let y = 44;

    /* ── Critical Alert Banner ── */
    if (labResult.is_critical) {
        doc.setFillColor(254, 226, 226);
        doc.roundedRect(14, y, pageW - 28, 28, 5, 5, 'F');
        doc.setFont('helvetica', 'bold'); doc.setFontSize(11); doc.setTextColor(185, 28, 28);
        doc.text('CRITICAL VALUES DETECTED - URGENT ATTENTION REQUIRED', pageW / 2, y + 18, { align: 'center' });
        y += 38;
    }

    /* ── Patient Info ── */
    y = _sectionLabel(doc, 'Patient Information', y);
    y = _table(doc, {
        startY: y,
        body: [
            ['Patient Name', patient.name || `${patient.first_name || ''} ${patient.last_name || ''}`.trim() || 'N/A'],
            ['Patient ID', patient.patient_id || 'N/A'],
            ['Test Date', labResult.test_date || 'N/A'],
            ['Ordered By', labResult.ordered_by_name || 'N/A'],
        ],
        columnStyles: { 0: { fontStyle: 'bold', cellWidth: 160, fillColor: LIGHT_GRAY } },
        bodyStyles: { fontSize: 9, cellPadding: 6 },
        alternateRowStyles: { fillColor: WHITE },
        margin: { left: 14, right: 14 },
        tableWidth: pageW - 28,
    }) + 12;

    /* ── Dialysis Adequacy (THE MOST IMPORTANT SECTION) ── */
    y = _sectionLabel(doc, 'Dialysis Adequacy (Key Metrics)', y);
    const adequacyRows = [];
    if (labResult.pre_dialysis_bun != null) adequacyRows.push(['Pre-Dialysis BUN', `${labResult.pre_dialysis_bun} mg/dL`, '-']);
    if (labResult.post_dialysis_bun != null) adequacyRows.push(['Post-Dialysis BUN', `${labResult.post_dialysis_bun} mg/dL`, '-']);
    if (labResult.urr != null) {
        const urrStatus = Number(labResult.urr) >= 65 ? 'ADEQUATE' : 'INADEQUATE';
        adequacyRows.push(['URR (Urea Reduction Ratio)', `${labResult.urr}%`, `Target: >=65% [${urrStatus}]`]);
    }
    if (labResult.ktv_estimated != null) {
        const ktvStatus = Number(labResult.ktv_estimated) >= 1.2 ? 'ADEQUATE' : 'INADEQUATE';
        adequacyRows.push(['Kt/V (Dialysis Dose)', `${labResult.ktv_estimated}`, `Target: >=1.2 [${ktvStatus}]`]);
    }
    if (adequacyRows.length > 0) {
        y = _table(doc, {
            startY: y,
            head: [['Test', 'Result', 'Reference']],
            body: adequacyRows,
            headStyles: { fillColor: [124, 58, 237], textColor: WHITE, fontStyle: 'bold', fontSize: 9 },
            bodyStyles: { fontSize: 9, textColor: DARK_COLOR },
            alternateRowStyles: { fillColor: [245, 243, 255] },
            margin: { left: 14, right: 14 },
            tableWidth: pageW - 28,
            columnStyles: { 0: { fontStyle: 'bold', cellWidth: 200 } },
        }) + 12;
    }

    /* ── Kidney Function ── */
    const kftRows = [];
    if (labResult.blood_urea_nitrogen != null) kftRows.push(['BUN', `${labResult.blood_urea_nitrogen} mg/dL`, '7-20 mg/dL']);
    if (labResult.serum_creatinine != null) kftRows.push(['Serum Creatinine', `${labResult.serum_creatinine} mg/dL`, '0.6-1.2 mg/dL']);
    if (kftRows.length > 0) {
        y = _sectionLabel(doc, 'Kidney Function Tests', y);
        y = _table(doc, {
            startY: y,
            head: [['Test', 'Result', 'Normal Range']],
            body: kftRows,
            headStyles: { fillColor: BRAND_COLOR, textColor: WHITE, fontStyle: 'bold', fontSize: 9 },
            bodyStyles: { fontSize: 8.5, textColor: DARK_COLOR },
            alternateRowStyles: { fillColor: [239, 246, 255] },
            margin: { left: 14, right: 14 },
            tableWidth: pageW - 28,
            columnStyles: { 0: { fontStyle: 'bold', cellWidth: 200 } },
        }) + 12;
    }

    /* ── CBC ── */
    const cbcRows = [];
    if (labResult.hemoglobin != null) {
        const hbFlag = Number(labResult.hemoglobin) < 8 ? ' ** CRITICAL LOW **' : '';
        cbcRows.push(['Hemoglobin', `${labResult.hemoglobin} g/dL${hbFlag}`, '10-12 g/dL (dialysis)']);
    }
    if (labResult.hematocrit != null) cbcRows.push(['Hematocrit', `${labResult.hematocrit}%`, '30-36%']);
    if (labResult.wbc_count != null) cbcRows.push(['WBC Count', `${labResult.wbc_count} x10^3/uL`, '4.5-11.0']);
    if (labResult.platelet_count != null) cbcRows.push(['Platelet Count', `${labResult.platelet_count} x10^3/uL`, '150-400']);
    if (cbcRows.length > 0) {
        y = _sectionLabel(doc, 'Complete Blood Count (CBC)', y);
        y = _table(doc, {
            startY: y,
            head: [['Test', 'Result', 'Normal Range']],
            body: cbcRows,
            headStyles: { fillColor: [220, 38, 38], textColor: WHITE, fontStyle: 'bold', fontSize: 9 },
            bodyStyles: { fontSize: 8.5, textColor: DARK_COLOR },
            alternateRowStyles: { fillColor: [254, 242, 242] },
            margin: { left: 14, right: 14 },
            tableWidth: pageW - 28,
            columnStyles: { 0: { fontStyle: 'bold', cellWidth: 200 } },
        }) + 12;
    }

    /* ── Electrolytes ── */
    const electroRows = [];
    if (labResult.serum_sodium != null) electroRows.push(['Sodium (Na+)', `${labResult.serum_sodium} mEq/L`, '135-145']);
    if (labResult.serum_potassium != null) {
        const kFlag = Number(labResult.serum_potassium) > 6.0 ? ' ** CRITICAL HIGH **' : '';
        electroRows.push(['Potassium (K+)', `${labResult.serum_potassium} mEq/L${kFlag}`, '3.5-5.0']);
    }
    if (labResult.serum_calcium != null) electroRows.push(['Calcium (Ca2+)', `${labResult.serum_calcium} mg/dL`, '8.5-10.5']);
    if (labResult.serum_phosphorus != null) electroRows.push(['Phosphorus', `${labResult.serum_phosphorus} mg/dL`, '2.5-4.5']);
    if (labResult.serum_bicarbonate != null) electroRows.push(['Bicarbonate', `${labResult.serum_bicarbonate} mEq/L`, '22-26']);
    if (electroRows.length > 0) {
        y = _sectionLabel(doc, 'Electrolytes', y);
        y = _table(doc, {
            startY: y,
            head: [['Test', 'Result', 'Normal Range']],
            body: electroRows,
            headStyles: { fillColor: [234, 179, 8], textColor: DARK_COLOR, fontStyle: 'bold', fontSize: 9 },
            bodyStyles: { fontSize: 8.5, textColor: DARK_COLOR },
            alternateRowStyles: { fillColor: [254, 252, 232] },
            margin: { left: 14, right: 14 },
            tableWidth: pageW - 28,
            columnStyles: { 0: { fontStyle: 'bold', cellWidth: 200 } },
        }) + 12;
    }

    /* ── Infection Screening ── */
    const infRows = [];
    if (labResult.hbsag) infRows.push(['HBsAg (Hepatitis B)', labResult.hbsag, 'Non-Reactive']);
    if (labResult.anti_hcv) infRows.push(['Anti-HCV (Hepatitis C)', labResult.anti_hcv, 'Non-Reactive']);
    if (labResult.hiv) infRows.push(['HIV', labResult.hiv, 'Non-Reactive']);
    if (infRows.length > 0) {
        y = _sectionLabel(doc, 'Infection Screening', y);
        y = _table(doc, {
            startY: y,
            head: [['Test', 'Result', 'Expected']],
            body: infRows,
            headStyles: { fillColor: [107, 33, 168], textColor: WHITE, fontStyle: 'bold', fontSize: 9 },
            bodyStyles: { fontSize: 8.5, textColor: DARK_COLOR },
            alternateRowStyles: { fillColor: [250, 245, 255] },
            margin: { left: 14, right: 14 },
            tableWidth: pageW - 28,
            columnStyles: { 0: { fontStyle: 'bold', cellWidth: 200 } },
        }) + 12;
    }

    _addFooter(doc);
    doc.save(`LabReport_${patient.patient_id || 'patient'}_${labResult.test_date || 'latest'}.pdf`);
}


// ─────────────────────────────────────────────────────────────────────────────
// 6. PATIENT SUMMARY PDF (includes infection, consent, prescription)
// ─────────────────────────────────────────────────────────────────────────────
export function downloadPatientSummaryPDF(patient) {
    const doc = new jsPDF({ unit: 'pt', format: 'a4' });
    const now = new Date().toLocaleString('en-IN', {
        day: '2-digit', month: 'short', year: 'numeric',
        hour: '2-digit', minute: '2-digit'
    });

    _addHeader(doc, 'PATIENT SUMMARY', `Generated: ${now}`);

    const pageW = doc.internal.pageSize.getWidth();
    let y = 44;

    /* ── Infection Alert Banner ── */
    if (patient.is_infection_positive) {
        doc.setFillColor(254, 226, 226);
        doc.roundedRect(14, y, pageW - 28, 24, 5, 5, 'F');
        doc.setFont('helvetica', 'bold'); doc.setFontSize(10); doc.setTextColor(185, 28, 28);
        doc.text('INFECTION POSITIVE - REQUIRES MACHINE ISOLATION', pageW / 2, y + 16, { align: 'center' });
        y += 32;
    }

    /* ── Personal Info ── */
    y = _sectionLabel(doc, 'Personal Information', y);
    y = _table(doc, {
        startY: y,
        body: [
            ['Patient ID', patient.patient_id || 'N/A'],
            ['Name', patient.full_name || `${patient.first_name || ''} ${patient.last_name || ''}`.trim() || 'N/A'],
            ['Date of Birth', patient.date_of_birth || 'N/A'],
            ['Age', patient.age != null ? `${patient.age} years` : 'N/A'],
            ['Gender', patient.gender || 'N/A'],
            ['Blood Type', patient.blood_type || 'N/A'],
            ['Phone', patient.phone_number || 'N/A'],
            ['Address', patient.address || 'N/A'],
            ['Emergency Contact', `${patient.emergency_contact_name || 'N/A'} - ${patient.emergency_contact_phone || 'N/A'}`],
        ],
        columnStyles: { 0: { fontStyle: 'bold', cellWidth: 160, fillColor: LIGHT_GRAY } },
        bodyStyles: { fontSize: 8.5, cellPadding: 6 },
        alternateRowStyles: { fillColor: WHITE },
        margin: { left: 14, right: 14 },
        tableWidth: pageW - 28,
    }) + 12;

    /* ── Medical Info ── */
    y = _sectionLabel(doc, 'Medical Information', y);
    y = _table(doc, {
        startY: y,
        body: [
            ['Primary Diagnosis', patient.primary_diagnosis || 'N/A'],
            ['Comorbidities', patient.comorbidities || 'None'],
            ['Allergies', patient.allergies || 'None known'],
            ['Current Medications', patient.current_medications || 'None'],
            ['Dialysis Type', patient.dialysis_type || 'N/A'],
            ['Vascular Access', patient.vascular_access || 'N/A'],
            ['Dry Weight', patient.dry_weight ? `${patient.dry_weight} kg` : 'N/A'],
        ],
        columnStyles: { 0: { fontStyle: 'bold', cellWidth: 160, fillColor: LIGHT_GRAY } },
        bodyStyles: { fontSize: 8.5, cellPadding: 6 },
        alternateRowStyles: { fillColor: WHITE },
        margin: { left: 14, right: 14 },
        tableWidth: pageW - 28,
    }) + 12;

    /* ── Infection Status ── */
    y = _sectionLabel(doc, 'Infection Status', y);
    const hbColor = patient.hepatitis_b_status === 'positive' ? [220, 38, 38] : DARK_COLOR;
    const hcColor = patient.hepatitis_c_status === 'positive' ? [220, 38, 38] : DARK_COLOR;
    const hivColor = patient.hiv_status === 'positive' ? [220, 38, 38] : DARK_COLOR;
    y = _table(doc, {
        startY: y,
        head: [['Test', 'Status', 'Last Screened']],
        body: [
            ['Hepatitis B (HBsAg)', (patient.hepatitis_b_status || 'Unknown').toUpperCase(), patient.last_infection_screening_date || 'Not tested'],
            ['Hepatitis C (Anti-HCV)', (patient.hepatitis_c_status || 'Unknown').toUpperCase(), patient.last_infection_screening_date || 'Not tested'],
            ['HIV', (patient.hiv_status || 'Unknown').toUpperCase(), patient.last_infection_screening_date || 'Not tested'],
            ['Hep B Vaccinated', patient.hepatitis_b_vaccinated ? 'YES' : 'NO', '-'],
        ],
        headStyles: { fillColor: [107, 33, 168], textColor: WHITE, fontStyle: 'bold', fontSize: 9 },
        bodyStyles: { fontSize: 8.5, textColor: DARK_COLOR },
        alternateRowStyles: { fillColor: [250, 245, 255] },
        margin: { left: 14, right: 14 },
        tableWidth: pageW - 28,
        columnStyles: { 0: { fontStyle: 'bold', cellWidth: 200 } },
    }) + 12;

    /* ── Consent Status ── */
    y = _sectionLabel(doc, 'Consent Status', y);
    const consentStatus = patient.is_consent_valid ? 'VALID' : 'EXPIRED / MISSING';
    const consentColor = patient.is_consent_valid ? GREEN_COLOR : [220, 38, 38];
    y = _table(doc, {
        startY: y,
        body: [
            ['Consent Given', patient.consent_given ? 'YES' : 'NO'],
            ['Consent Date', patient.consent_date || 'N/A'],
            ['Consent Expiry', patient.consent_expiry_date || 'N/A'],
            ['Status', consentStatus],
        ],
        columnStyles: { 0: { fontStyle: 'bold', cellWidth: 160, fillColor: LIGHT_GRAY } },
        bodyStyles: { fontSize: 8.5, cellPadding: 6 },
        alternateRowStyles: { fillColor: WHITE },
        margin: { left: 14, right: 14 },
        tableWidth: pageW - 28,
    }) + 12;

    /* ── Active Prescription Summary ── */
    if (patient.active_prescription) {
        const rx = patient.active_prescription;
        y = _sectionLabel(doc, 'Active Prescription', y);
        y = _table(doc, {
            startY: y,
            body: [
                ['Frequency', rx.frequency || 'N/A'],
                ['Duration', rx.duration_minutes ? `${rx.duration_minutes} min` : 'N/A'],
                ['Blood Flow Rate', rx.blood_flow_rate ? `${rx.blood_flow_rate} ml/min` : 'N/A'],
                ['Dialyzer', rx.dialyzer_type || 'N/A'],
                ['Prescribed By', rx.prescribed_by || 'N/A'],
                ['Effective From', rx.effective_date || 'N/A'],
            ],
            columnStyles: { 0: { fontStyle: 'bold', cellWidth: 160, fillColor: [240, 253, 244] } },
            bodyStyles: { fontSize: 8.5, cellPadding: 6 },
            alternateRowStyles: { fillColor: WHITE },
            margin: { left: 14, right: 14 },
            tableWidth: pageW - 28,
        }) + 12;
    }

    _addFooter(doc);
    doc.save(`Patient_${patient.patient_id || 'summary'}.pdf`);
}
