# Generated by Django 4.2.7 on 2026-01-08 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('doctor', 'Doctor'), ('nurse', 'Nurse'), ('technician', 'Technician'), ('receptionist', 'Receptionist'), ('patient', 'Patient')], default='receptionist', max_length=20),
        ),
    ]
