# Generated by Django 4.2.7 on 2026-02-23 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_user_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('doctor', 'Doctor'), ('nurse', 'Nurse'), ('technician', 'Technician'), ('receptionist', 'Receptionist'), ('patient', 'Patient'), ('driver', 'Driver')], default='receptionist', max_length=20),
        ),
    ]
